version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: pulsenews
      POSTGRES_USER: pulsenews
      POSTGRES_PASSWORD: pulsenews
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  web:
    build: .
    command: bash -c "python manage.py migrate && gunicorn pulse_news.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  celery:
    build: .
    command: celery -A pulse_news worker -l info
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      - redis
      - db

  celery-beat:
    build: .
    command: celery -A pulse_news beat -l info
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      - redis
      - db

volumes:
  postgres_data:
